# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Barry Chen
email: spchen38@163.com
description: console.log("I am Adobe.");
baseurl: /chen38.github.io
url: "http://chen38.github.io/"
weibo_username: Cyb不是葱油饼
github_username: Chen38
wechat_uername: 葱油饼

# Build settings
markdown: kramdown
